### ISSUE TITLE
L2B_Segmnetation missing ''from Models.Unetplpl_2D import NestedUNet''

### ISSUE THREAD

**Issue by Kedaya66** [yuyinzhou/L2B#5]
Dear author:
Thanks for your contributions to noisy label learning. Now, I am trying to reimplement your work on segmentation task. However, it seems that the ''Models.Unetplpl_2D import NestedUNet'' isn't provided. Could you please upload this python file for better reimplementation. Thanks again!

**Comment by Kedaya66** [comment]
after running script ''data_preprocess.py'', the ''meta_train_scan3 directory is empty. This affects the running of ''train.py'' script and has the following bug existed.
![Uploading image.png…]()

**Comment by Kedaya66** [comment]
dataset: Prostate Norm_type org
Img size: [144, 144]
Experiments is conducted on: baseline_Unet++_2d_ema
==> Preparing data..
Traceback (most recent call last):
  File "E:\Anaconda\envs\dl\lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3, 512), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\works\mission\Exploring\Z-CodesPool\L2B-main\L2B_segmentation\train.py", line 344, in <module>
    main(args)
  File "D:\works\mission\Exploring\Z-CodesPool\L2B-main\L2B_segmentation\train.py", line 147, in main
    val_data, val_labels = next(iter(metaloader))
  File "E:\Anaconda\envs\dl\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "E:\Anaconda\envs\dl\lib\site-packages\torch\utils\data\dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\Anaconda\envs\dl\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Anaconda\envs\dl\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\works\mission\Exploring\Z-CodesPool\L2B-main\L2B_segmentation\dataloader.py", line 176, in __getitem__
    img = Image.fromarray(np.expand_dims(img, 2).repeat(3, 2))
  File "E:\Anaconda\envs\dl\lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 3, 512), |u1
